[project]
name = "qq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colorama>=0.4.6",
    "fastapi>=0.115.12",
    "psutil>=7.0.0",
    "pynvml>=12.0.0",
    "uvicorn>=0.34.2",
    "websockets>=15.0.1",
]
